POST http://localhost:5005/api/notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0ODMyMjkwMiwiZXhwIjoxNzQ4MzI2NTAyfQ.2-cTdfhRXQVKbAakR6KwKmCO5FY6i0Hl4pdfd9Dnb84

{
  "type": "EXCHANGE_PROPOSED",
  "content": "교환 제안이 도착했어요!" 
}

###
GET http://localhost:5005/api/notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJpYXQiOjE3NDg5OTY2MzMsImV4cCI6MTc0OTAwMDIzM30.16u9eWNpbw9YkXAk1bLOdJl1ArBJsEkQ-bRz-v3ojm4

###
PATCH http://localhost:5005/api/notification/1/read

### 로그인 테스트 (유저 로그인)
POST http://localhost:5005/auth/signin
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "1234"
}