### 쿨타임 확인
GET http://localhost:5005/api/users/me/point/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0ODQxMTM2OCwiZXhwIjoxNzQ4NDE0OTY4fQ.PIKzPooMQVrixZ_ZbrgFXUAqMMc9v0RnRbjjuDsOgRc
Content-Type: application/json


### 포인트 뽑기
POST http://localhost:5005/api/users/me/point/draw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0ODQxMTM2OCwiZXhwIjoxNzQ4NDE0OTY4fQ.PIKzPooMQVrixZ_ZbrgFXUAqMMc9v0RnRbjjuDsOgRc
Content-Type: application/json